package com.example.data.remote

/**
 * Input metadata representing a product to be optimized by Gemini AI.
 */
data class ProductMetadata(
    val title: String,
    val brand: String? = null,
    val category: String? = null,
    val subCategory: String? = null,
    val attributes: Map<String, String> = emptyMap(), // e.g., "Material" -> "100% Organic Cotton", "Color" -> "Navy Blue"
    val keyFeatures: List<String> = emptyList(),
    val targetAudience: String? = null, // e.g., "Men", "Women", "Unisex", "Kids", "Home Enthusiasts"
    val price: Double? = null,
    val originalPrice: Double? = null,
    val currency: String = "₺",
    val keywords: List<String> = emptyList(),
    val tone: String = "احترافي وجذاب ومحفز للشراء", // e.g., "Professional & Persuasive", "Trendy", "Luxury"
    val language: String = "العربية والتركية (Bilingual)", // "Arabic", "Turkish", "Bilingual"
    val targetMarketplace: String = "Trendyol"
) {
    /**
     * Formats the metadata into a clear structured prompt for Gemini.
     */
    fun toPromptDescription(): String {
        val sb = StringBuilder()
        sb.appendLine("بيانات ومعلومات المنتج الوصفية (Product Metadata):")
        sb.appendLine("- اسم / نوع المنتج الأساسي: $title")
        if (!brand.isNullOrBlank()) sb.appendLine("- العلامة التجارية (Marka): $brand")
        if (!category.isNullOrBlank()) sb.appendLine("- الفئة الرئيسية (Kategori): $category")
        if (!subCategory.isNullOrBlank()) sb.appendLine("- الفئة الفرعية: $subCategory")
        if (price != null && price > 0) sb.appendLine("- سعر البيع الحالي: $price $currency")
        if (originalPrice != null && originalPrice > 0) sb.appendLine("- السعر قبل الخصم: $originalPrice $currency")
        if (!targetAudience.isNullOrBlank()) sb.appendLine("- الفئة المستهدفة: $targetAudience")

        if (attributes.isNotEmpty()) {
            sb.appendLine("- الخصائص والمواصفات التفصيلية:")
            attributes.forEach { (key, value) ->
                sb.appendLine("  • $key: $value")
            }
        }

        if (keyFeatures.isNotEmpty()) {
            sb.appendLine("- المزايا التنافسية ونقاط البيع الفريدة (USPs):")
            keyFeatures.forEach { feature ->
                sb.appendLine("  • $feature")
            }
        }

        if (keywords.isNotEmpty()) {
            sb.appendLine("- الكلمات المفتاحية المستهدفة: ${keywords.joinToString(", ")}")
        }

        sb.appendLine("- النبرة المطلوبة: $tone")
        sb.appendLine("- لغة العرض: $language")
        sb.appendLine("- منصة البيع المستهدفة: $targetMarketplace")

        return sb.toString()
    }
}

/**
 * Output data class containing structured, optimized product description fields generated by Gemini.
 */
data class OptimizedProductDescription(
    val seoTitle: String,
    val shortSummary: String,
    val highlightBullets: List<String>,
    val fullDescription: String,
    val technicalSpecs: Map<String, String>,
    val searchTags: List<String>,
    val rawFormattedOutput: String
)
